image: alpine/edge
packages:
  - nodejs
  - npm
oauth: pages.sr.ht/PAGES:RW
environment:
  site: thick.rocks
tasks:
  - setup: |
      cd $site
      npm ci
      npm run build
  - package: |
      cd $site
      tar -C output -cvz . > ../site.tar.gz
  - upload: |
      acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
